/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/apply-for-graduate-student': RouteRecordInfo<
      '/posts/apply-for-graduate-student',
      '/posts/apply-for-graduate-student',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/comic-magazines': RouteRecordInfo<
      '/posts/comic-magazines',
      '/posts/comic-magazines',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/csapp-notes': RouteRecordInfo<
      '/posts/csapp-notes',
      '/posts/csapp-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/db2': RouteRecordInfo<
      '/posts/db2',
      '/posts/db2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/deep-learning-notes': RouteRecordInfo<
      '/posts/deep-learning-notes',
      '/posts/deep-learning-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/diary1': RouteRecordInfo<
      '/posts/diary1',
      '/posts/diary1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gaokao-1': RouteRecordInfo<
      '/posts/gaokao-1',
      '/posts/gaokao-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/goodbye-forever-c': RouteRecordInfo<
      '/posts/goodbye-forever-c',
      '/posts/goodbye-forever-c',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gpa-calculator': RouteRecordInfo<
      '/posts/gpa-calculator',
      '/posts/gpa-calculator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/heyiwei': RouteRecordInfo<
      '/posts/heyiwei',
      '/posts/heyiwei',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java-review-notes': RouteRecordInfo<
      '/posts/java-review-notes',
      '/posts/java-review-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/js-review-notes': RouteRecordInfo<
      '/posts/js-review-notes',
      '/posts/js-review-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/machine-learning-basics': RouteRecordInfo<
      '/posts/machine-learning-basics',
      '/posts/machine-learning-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ml-final-2024': RouteRecordInfo<
      '/posts/ml-final-2024',
      '/posts/ml-final-2024',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/normal-distribution-generate': RouteRecordInfo<
      '/posts/normal-distribution-generate',
      '/posts/normal-distribution-generate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/oop-addition': RouteRecordInfo<
      '/posts/oop-addition',
      '/posts/oop-addition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/oop-test-paper': RouteRecordInfo<
      '/posts/oop-test-paper',
      '/posts/oop-test-paper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python-review-notes': RouteRecordInfo<
      '/posts/python-review-notes',
      '/posts/python-review-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/software-engineering-notes': RouteRecordInfo<
      '/posts/software-engineering-notes',
      '/posts/software-engineering-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy': RouteRecordInfo<
      '/posts/valaxy',
      '/posts/valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/': RouteRecordInfo<
      '/tools/',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/random-gen': RouteRecordInfo<
      '/tools/random-gen',
      '/tools/random-gen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.8_mag_9bcc89a3045b97fb44840e9820e926f7/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.8_@babel+parser_44f63cd86840722f564e6d3332198978/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.8_mag_9bcc89a3045b97fb44840e9820e926f7/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.8_mag_9bcc89a3045b97fb44840e9820e926f7/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/apply-for-graduate-student.md': {
      routes:
        | '/posts/apply-for-graduate-student'
      views:
        | never
    }
    'pages/posts/comic-magazines.md': {
      routes:
        | '/posts/comic-magazines'
      views:
        | never
    }
    'pages/posts/csapp-notes.md': {
      routes:
        | '/posts/csapp-notes'
      views:
        | never
    }
    'pages/posts/db2.md': {
      routes:
        | '/posts/db2'
      views:
        | never
    }
    'pages/posts/deep-learning-notes.md': {
      routes:
        | '/posts/deep-learning-notes'
      views:
        | never
    }
    'pages/posts/diary1.md': {
      routes:
        | '/posts/diary1'
      views:
        | never
    }
    'pages/posts/gaokao-1.md': {
      routes:
        | '/posts/gaokao-1'
      views:
        | never
    }
    'pages/posts/goodbye-forever-c.md': {
      routes:
        | '/posts/goodbye-forever-c'
      views:
        | never
    }
    'pages/posts/gpa-calculator.md': {
      routes:
        | '/posts/gpa-calculator'
      views:
        | never
    }
    'pages/posts/heyiwei.md': {
      routes:
        | '/posts/heyiwei'
      views:
        | never
    }
    'pages/posts/java-review-notes.md': {
      routes:
        | '/posts/java-review-notes'
      views:
        | never
    }
    'pages/posts/js-review-notes.md': {
      routes:
        | '/posts/js-review-notes'
      views:
        | never
    }
    'pages/posts/machine-learning-basics.md': {
      routes:
        | '/posts/machine-learning-basics'
      views:
        | never
    }
    'pages/posts/ml-final-2024.md': {
      routes:
        | '/posts/ml-final-2024'
      views:
        | never
    }
    'pages/posts/normal-distribution-generate.md': {
      routes:
        | '/posts/normal-distribution-generate'
      views:
        | never
    }
    'pages/posts/oop-addition.md': {
      routes:
        | '/posts/oop-addition'
      views:
        | never
    }
    'pages/posts/oop-test-paper.md': {
      routes:
        | '/posts/oop-test-paper'
      views:
        | never
    }
    'pages/posts/python-review-notes.md': {
      routes:
        | '/posts/python-review-notes'
      views:
        | never
    }
    'pages/posts/software-engineering-notes.md': {
      routes:
        | '/posts/software-engineering-notes'
      views:
        | never
    }
    'pages/posts/valaxy.md': {
      routes:
        | '/posts/valaxy'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
    'pages/tools/index.md': {
      routes:
        | '/tools/'
      views:
        | never
    }
    'pages/tools/random-gen.md': {
      routes:
        | '/tools/random-gen'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
